//! Opcode metadata for disassembly. Pure data — no execution logic.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AddressingMode {
    Implied,
    Accumulator,
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Relative,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndexedIndirect,
    IndirectIndexed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mnemonic {
    Adc,
    And,
    Asl,
    Bcc,
    Bcs,
    Beq,
    Bit,
    Bmi,
    Bne,
    Bpl,
    Brk,
    Bvc,
    Bvs,
    Clc,
    Cld,
    Cli,
    Clv,
    Cmp,
    Cpx,
    Cpy,
    Dec,
    Dex,
    Dey,
    Eor,
    Inc,
    Inx,
    Iny,
    Jmp,
    Jsr,
    Lda,
    Ldx,
    Ldy,
    Lsr,
    Nop,
    Ora,
    Pha,
    Php,
    Pla,
    Plp,
    Rol,
    Ror,
    Rti,
    Rts,
    Sbc,
    Sec,
    Sed,
    Sei,
    Sta,
    Stx,
    Sty,
    Tax,
    Tay,
    Tsx,
    Txa,
    Txs,
    Tya,
    // Unofficial
    Dcp,
    Isc,
    Lax,
    Rla,
    Rra,
    Sax,
    Slo,
    Sre,
    Illegal,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InstructionInfo {
    pub opcode: u8,
    pub mnemonic: Mnemonic,
    pub mode: AddressingMode,
    pub cycles: u8,
}

impl AddressingMode {
    pub fn operand_count(&self) -> usize {
        match self {
            AddressingMode::Implied | AddressingMode::Accumulator => 0,
            AddressingMode::Immediate
            | AddressingMode::ZeroPage
            | AddressingMode::ZeroPageX
            | AddressingMode::ZeroPageY
            | AddressingMode::Relative
            | AddressingMode::IndexedIndirect
            | AddressingMode::IndirectIndexed => 1,
            AddressingMode::Absolute
            | AddressingMode::AbsoluteX
            | AddressingMode::AbsoluteY
            | AddressingMode::Indirect => 2,
        }
    }
}

const fn info(opcode: u8, mnemonic: Mnemonic, mode: AddressingMode, cycles: u8) -> InstructionInfo {
    InstructionInfo {
        opcode,
        mnemonic,
        mode,
        cycles,
    }
}

pub const fn decode(opcode: u8) -> InstructionInfo {
    match opcode {
        0x00 => info(0x00, Mnemonic::Brk, AddressingMode::Implied, 7),
        0x01 => info(0x01, Mnemonic::Ora, AddressingMode::IndexedIndirect, 6),
        0x03 => info(0x03, Mnemonic::Slo, AddressingMode::IndexedIndirect, 8),
        0x05 => info(0x05, Mnemonic::Ora, AddressingMode::ZeroPage, 3),
        0x06 => info(0x06, Mnemonic::Asl, AddressingMode::ZeroPage, 5),
        0x07 => info(0x07, Mnemonic::Slo, AddressingMode::ZeroPage, 5),
        0x08 => info(0x08, Mnemonic::Php, AddressingMode::Implied, 3),
        0x09 => info(0x09, Mnemonic::Ora, AddressingMode::Immediate, 2),
        0x0A => info(0x0A, Mnemonic::Asl, AddressingMode::Accumulator, 2),
        0x0D => info(0x0D, Mnemonic::Ora, AddressingMode::Absolute, 4),
        0x0E => info(0x0E, Mnemonic::Asl, AddressingMode::Absolute, 6),
        0x0F => info(0x0F, Mnemonic::Slo, AddressingMode::Absolute, 6),
        0x10 => info(0x10, Mnemonic::Bpl, AddressingMode::Relative, 2),
        0x11 => info(0x11, Mnemonic::Ora, AddressingMode::IndirectIndexed, 5),
        0x13 => info(0x13, Mnemonic::Slo, AddressingMode::IndirectIndexed, 8),
        0x15 => info(0x15, Mnemonic::Ora, AddressingMode::ZeroPageX, 4),
        0x16 => info(0x16, Mnemonic::Asl, AddressingMode::ZeroPageX, 6),
        0x17 => info(0x17, Mnemonic::Slo, AddressingMode::ZeroPageX, 6),
        0x18 => info(0x18, Mnemonic::Clc, AddressingMode::Implied, 2),
        0x19 => info(0x19, Mnemonic::Ora, AddressingMode::AbsoluteY, 4),
        0x1B => info(0x1B, Mnemonic::Slo, AddressingMode::AbsoluteY, 7),
        0x1D => info(0x1D, Mnemonic::Ora, AddressingMode::AbsoluteX, 4),
        0x1E => info(0x1E, Mnemonic::Asl, AddressingMode::AbsoluteX, 7),
        0x1F => info(0x1F, Mnemonic::Slo, AddressingMode::AbsoluteX, 7),
        0x20 => info(0x20, Mnemonic::Jsr, AddressingMode::Absolute, 6),
        0x21 => info(0x21, Mnemonic::And, AddressingMode::IndexedIndirect, 6),
        0x23 => info(0x23, Mnemonic::Rla, AddressingMode::IndexedIndirect, 8),
        0x24 => info(0x24, Mnemonic::Bit, AddressingMode::ZeroPage, 3),
        0x25 => info(0x25, Mnemonic::And, AddressingMode::ZeroPage, 3),
        0x26 => info(0x26, Mnemonic::Rol, AddressingMode::ZeroPage, 5),
        0x27 => info(0x27, Mnemonic::Rla, AddressingMode::ZeroPage, 5),
        0x28 => info(0x28, Mnemonic::Plp, AddressingMode::Implied, 4),
        0x29 => info(0x29, Mnemonic::And, AddressingMode::Immediate, 2),
        0x2A => info(0x2A, Mnemonic::Rol, AddressingMode::Accumulator, 2),
        0x2C => info(0x2C, Mnemonic::Bit, AddressingMode::Absolute, 4),
        0x2D => info(0x2D, Mnemonic::And, AddressingMode::Absolute, 4),
        0x2E => info(0x2E, Mnemonic::Rol, AddressingMode::Absolute, 6),
        0x2F => info(0x2F, Mnemonic::Rla, AddressingMode::Absolute, 6),
        0x30 => info(0x30, Mnemonic::Bmi, AddressingMode::Relative, 2),
        0x31 => info(0x31, Mnemonic::And, AddressingMode::IndirectIndexed, 5),
        0x33 => info(0x33, Mnemonic::Rla, AddressingMode::IndirectIndexed, 8),
        0x35 => info(0x35, Mnemonic::And, AddressingMode::ZeroPageX, 4),
        0x36 => info(0x36, Mnemonic::Rol, AddressingMode::ZeroPageX, 6),
        0x37 => info(0x37, Mnemonic::Rla, AddressingMode::ZeroPageX, 6),
        0x38 => info(0x38, Mnemonic::Sec, AddressingMode::Implied, 2),
        0x39 => info(0x39, Mnemonic::And, AddressingMode::AbsoluteY, 4),
        0x3B => info(0x3B, Mnemonic::Rla, AddressingMode::AbsoluteY, 7),
        0x3D => info(0x3D, Mnemonic::And, AddressingMode::AbsoluteX, 4),
        0x3E => info(0x3E, Mnemonic::Rol, AddressingMode::AbsoluteX, 7),
        0x3F => info(0x3F, Mnemonic::Rla, AddressingMode::AbsoluteX, 7),
        0x40 => info(0x40, Mnemonic::Rti, AddressingMode::Implied, 6),
        0x41 => info(0x41, Mnemonic::Eor, AddressingMode::IndexedIndirect, 6),
        0x43 => info(0x43, Mnemonic::Sre, AddressingMode::IndexedIndirect, 8),
        0x45 => info(0x45, Mnemonic::Eor, AddressingMode::ZeroPage, 3),
        0x46 => info(0x46, Mnemonic::Lsr, AddressingMode::ZeroPage, 5),
        0x47 => info(0x47, Mnemonic::Sre, AddressingMode::ZeroPage, 5),
        0x48 => info(0x48, Mnemonic::Pha, AddressingMode::Implied, 3),
        0x49 => info(0x49, Mnemonic::Eor, AddressingMode::Immediate, 2),
        0x4A => info(0x4A, Mnemonic::Lsr, AddressingMode::Accumulator, 2),
        0x4C => info(0x4C, Mnemonic::Jmp, AddressingMode::Absolute, 3),
        0x4D => info(0x4D, Mnemonic::Eor, AddressingMode::Absolute, 4),
        0x4E => info(0x4E, Mnemonic::Lsr, AddressingMode::Absolute, 6),
        0x4F => info(0x4F, Mnemonic::Sre, AddressingMode::Absolute, 6),
        0x50 => info(0x50, Mnemonic::Bvc, AddressingMode::Relative, 2),
        0x51 => info(0x51, Mnemonic::Eor, AddressingMode::IndirectIndexed, 5),
        0x53 => info(0x53, Mnemonic::Sre, AddressingMode::IndirectIndexed, 8),
        0x55 => info(0x55, Mnemonic::Eor, AddressingMode::ZeroPageX, 4),
        0x56 => info(0x56, Mnemonic::Lsr, AddressingMode::ZeroPageX, 6),
        0x57 => info(0x57, Mnemonic::Sre, AddressingMode::ZeroPageX, 6),
        0x58 => info(0x58, Mnemonic::Cli, AddressingMode::Implied, 2),
        0x59 => info(0x59, Mnemonic::Eor, AddressingMode::AbsoluteY, 4),
        0x5B => info(0x5B, Mnemonic::Sre, AddressingMode::AbsoluteY, 7),
        0x5D => info(0x5D, Mnemonic::Eor, AddressingMode::AbsoluteX, 4),
        0x5E => info(0x5E, Mnemonic::Lsr, AddressingMode::AbsoluteX, 7),
        0x5F => info(0x5F, Mnemonic::Sre, AddressingMode::AbsoluteX, 7),
        0x60 => info(0x60, Mnemonic::Rts, AddressingMode::Implied, 6),
        0x61 => info(0x61, Mnemonic::Adc, AddressingMode::IndexedIndirect, 6),
        0x63 => info(0x63, Mnemonic::Rra, AddressingMode::IndexedIndirect, 8),
        0x65 => info(0x65, Mnemonic::Adc, AddressingMode::ZeroPage, 3),
        0x66 => info(0x66, Mnemonic::Ror, AddressingMode::ZeroPage, 5),
        0x67 => info(0x67, Mnemonic::Rra, AddressingMode::ZeroPage, 5),
        0x68 => info(0x68, Mnemonic::Pla, AddressingMode::Implied, 4),
        0x69 => info(0x69, Mnemonic::Adc, AddressingMode::Immediate, 2),
        0x6A => info(0x6A, Mnemonic::Ror, AddressingMode::Accumulator, 2),
        0x6C => info(0x6C, Mnemonic::Jmp, AddressingMode::Indirect, 5),
        0x6D => info(0x6D, Mnemonic::Adc, AddressingMode::Absolute, 4),
        0x6E => info(0x6E, Mnemonic::Ror, AddressingMode::Absolute, 6),
        0x6F => info(0x6F, Mnemonic::Rra, AddressingMode::Absolute, 6),
        0x70 => info(0x70, Mnemonic::Bvs, AddressingMode::Relative, 2),
        0x71 => info(0x71, Mnemonic::Adc, AddressingMode::IndirectIndexed, 5),
        0x73 => info(0x73, Mnemonic::Rra, AddressingMode::IndirectIndexed, 8),
        0x75 => info(0x75, Mnemonic::Adc, AddressingMode::ZeroPageX, 4),
        0x76 => info(0x76, Mnemonic::Ror, AddressingMode::ZeroPageX, 6),
        0x77 => info(0x77, Mnemonic::Rra, AddressingMode::ZeroPageX, 6),
        0x78 => info(0x78, Mnemonic::Sei, AddressingMode::Implied, 2),
        0x79 => info(0x79, Mnemonic::Adc, AddressingMode::AbsoluteY, 4),
        0x7B => info(0x7B, Mnemonic::Rra, AddressingMode::AbsoluteY, 7),
        0x7D => info(0x7D, Mnemonic::Adc, AddressingMode::AbsoluteX, 4),
        0x7E => info(0x7E, Mnemonic::Ror, AddressingMode::AbsoluteX, 7),
        0x7F => info(0x7F, Mnemonic::Rra, AddressingMode::AbsoluteX, 7),
        0x81 => info(0x81, Mnemonic::Sta, AddressingMode::IndexedIndirect, 6),
        0x83 => info(0x83, Mnemonic::Sax, AddressingMode::IndexedIndirect, 6),
        0x84 => info(0x84, Mnemonic::Sty, AddressingMode::ZeroPage, 3),
        0x85 => info(0x85, Mnemonic::Sta, AddressingMode::ZeroPage, 3),
        0x86 => info(0x86, Mnemonic::Stx, AddressingMode::ZeroPage, 3),
        0x87 => info(0x87, Mnemonic::Sax, AddressingMode::ZeroPage, 3),
        0x88 => info(0x88, Mnemonic::Dey, AddressingMode::Implied, 2),
        0x8A => info(0x8A, Mnemonic::Txa, AddressingMode::Implied, 2),
        0x8C => info(0x8C, Mnemonic::Sty, AddressingMode::Absolute, 4),
        0x8D => info(0x8D, Mnemonic::Sta, AddressingMode::Absolute, 4),
        0x8E => info(0x8E, Mnemonic::Stx, AddressingMode::Absolute, 4),
        0x8F => info(0x8F, Mnemonic::Sax, AddressingMode::Absolute, 4),
        0x90 => info(0x90, Mnemonic::Bcc, AddressingMode::Relative, 2),
        0x91 => info(0x91, Mnemonic::Sta, AddressingMode::IndirectIndexed, 6),
        0x94 => info(0x94, Mnemonic::Sty, AddressingMode::ZeroPageX, 4),
        0x95 => info(0x95, Mnemonic::Sta, AddressingMode::ZeroPageX, 4),
        0x96 => info(0x96, Mnemonic::Stx, AddressingMode::ZeroPageY, 4),
        0x97 => info(0x97, Mnemonic::Sax, AddressingMode::ZeroPageY, 4),
        0x98 => info(0x98, Mnemonic::Tya, AddressingMode::Implied, 2),
        0x99 => info(0x99, Mnemonic::Sta, AddressingMode::AbsoluteY, 5),
        0x9A => info(0x9A, Mnemonic::Txs, AddressingMode::Implied, 2),
        0x9D => info(0x9D, Mnemonic::Sta, AddressingMode::AbsoluteX, 5),
        0xA0 => info(0xA0, Mnemonic::Ldy, AddressingMode::Immediate, 2),
        0xA1 => info(0xA1, Mnemonic::Lda, AddressingMode::IndexedIndirect, 6),
        0xA2 => info(0xA2, Mnemonic::Ldx, AddressingMode::Immediate, 2),
        0xA3 => info(0xA3, Mnemonic::Lax, AddressingMode::IndexedIndirect, 6),
        0xA4 => info(0xA4, Mnemonic::Ldy, AddressingMode::ZeroPage, 3),
        0xA5 => info(0xA5, Mnemonic::Lda, AddressingMode::ZeroPage, 3),
        0xA6 => info(0xA6, Mnemonic::Ldx, AddressingMode::ZeroPage, 3),
        0xA7 => info(0xA7, Mnemonic::Lax, AddressingMode::ZeroPage, 3),
        0xA8 => info(0xA8, Mnemonic::Tay, AddressingMode::Implied, 2),
        0xA9 => info(0xA9, Mnemonic::Lda, AddressingMode::Immediate, 2),
        0xAA => info(0xAA, Mnemonic::Tax, AddressingMode::Implied, 2),
        0xAC => info(0xAC, Mnemonic::Ldy, AddressingMode::Absolute, 4),
        0xAD => info(0xAD, Mnemonic::Lda, AddressingMode::Absolute, 4),
        0xAE => info(0xAE, Mnemonic::Ldx, AddressingMode::Absolute, 4),
        0xAF => info(0xAF, Mnemonic::Lax, AddressingMode::Absolute, 4),
        0xB0 => info(0xB0, Mnemonic::Bcs, AddressingMode::Relative, 2),
        0xB1 => info(0xB1, Mnemonic::Lda, AddressingMode::IndirectIndexed, 5),
        0xB3 => info(0xB3, Mnemonic::Lax, AddressingMode::IndirectIndexed, 5),
        0xB4 => info(0xB4, Mnemonic::Ldy, AddressingMode::ZeroPageX, 4),
        0xB5 => info(0xB5, Mnemonic::Lda, AddressingMode::ZeroPageX, 4),
        0xB6 => info(0xB6, Mnemonic::Ldx, AddressingMode::ZeroPageY, 4),
        0xB7 => info(0xB7, Mnemonic::Lax, AddressingMode::ZeroPageY, 4),
        0xB8 => info(0xB8, Mnemonic::Clv, AddressingMode::Implied, 2),
        0xB9 => info(0xB9, Mnemonic::Lda, AddressingMode::AbsoluteY, 4),
        0xBA => info(0xBA, Mnemonic::Tsx, AddressingMode::Implied, 2),
        0xBC => info(0xBC, Mnemonic::Ldy, AddressingMode::AbsoluteX, 4),
        0xBD => info(0xBD, Mnemonic::Lda, AddressingMode::AbsoluteX, 4),
        0xBE => info(0xBE, Mnemonic::Ldx, AddressingMode::AbsoluteY, 4),
        0xBF => info(0xBF, Mnemonic::Lax, AddressingMode::AbsoluteY, 4),
        0xC0 => info(0xC0, Mnemonic::Cpy, AddressingMode::Immediate, 2),
        0xC1 => info(0xC1, Mnemonic::Cmp, AddressingMode::IndexedIndirect, 6),
        0xC3 => info(0xC3, Mnemonic::Dcp, AddressingMode::IndexedIndirect, 8),
        0xC4 => info(0xC4, Mnemonic::Cpy, AddressingMode::ZeroPage, 3),
        0xC5 => info(0xC5, Mnemonic::Cmp, AddressingMode::ZeroPage, 3),
        0xC6 => info(0xC6, Mnemonic::Dec, AddressingMode::ZeroPage, 5),
        0xC7 => info(0xC7, Mnemonic::Dcp, AddressingMode::ZeroPage, 5),
        0xC8 => info(0xC8, Mnemonic::Iny, AddressingMode::Implied, 2),
        0xC9 => info(0xC9, Mnemonic::Cmp, AddressingMode::Immediate, 2),
        0xCA => info(0xCA, Mnemonic::Dex, AddressingMode::Implied, 2),
        0xCC => info(0xCC, Mnemonic::Cpy, AddressingMode::Absolute, 4),
        0xCD => info(0xCD, Mnemonic::Cmp, AddressingMode::Absolute, 4),
        0xCE => info(0xCE, Mnemonic::Dec, AddressingMode::Absolute, 6),
        0xCF => info(0xCF, Mnemonic::Dcp, AddressingMode::Absolute, 6),
        0xD0 => info(0xD0, Mnemonic::Bne, AddressingMode::Relative, 2),
        0xD1 => info(0xD1, Mnemonic::Cmp, AddressingMode::IndirectIndexed, 5),
        0xD3 => info(0xD3, Mnemonic::Dcp, AddressingMode::IndirectIndexed, 8),
        0xD5 => info(0xD5, Mnemonic::Cmp, AddressingMode::ZeroPageX, 4),
        0xD6 => info(0xD6, Mnemonic::Dec, AddressingMode::ZeroPageX, 6),
        0xD7 => info(0xD7, Mnemonic::Dcp, AddressingMode::ZeroPageX, 6),
        0xD8 => info(0xD8, Mnemonic::Cld, AddressingMode::Implied, 2),
        0xD9 => info(0xD9, Mnemonic::Cmp, AddressingMode::AbsoluteY, 4),
        0xDB => info(0xDB, Mnemonic::Dcp, AddressingMode::AbsoluteY, 7),
        0xDD => info(0xDD, Mnemonic::Cmp, AddressingMode::AbsoluteX, 4),
        0xDE => info(0xDE, Mnemonic::Dec, AddressingMode::AbsoluteX, 7),
        0xDF => info(0xDF, Mnemonic::Dcp, AddressingMode::AbsoluteX, 7),
        0xE0 => info(0xE0, Mnemonic::Cpx, AddressingMode::Immediate, 2),
        0xE1 => info(0xE1, Mnemonic::Sbc, AddressingMode::IndexedIndirect, 6),
        0xE3 => info(0xE3, Mnemonic::Isc, AddressingMode::IndexedIndirect, 8),
        0xE4 => info(0xE4, Mnemonic::Cpx, AddressingMode::ZeroPage, 3),
        0xE5 => info(0xE5, Mnemonic::Sbc, AddressingMode::ZeroPage, 3),
        0xE6 => info(0xE6, Mnemonic::Inc, AddressingMode::ZeroPage, 5),
        0xE7 => info(0xE7, Mnemonic::Isc, AddressingMode::ZeroPage, 5),
        0xE8 => info(0xE8, Mnemonic::Inx, AddressingMode::Implied, 2),
        0xE9 => info(0xE9, Mnemonic::Sbc, AddressingMode::Immediate, 2),
        0xEA => info(0xEA, Mnemonic::Nop, AddressingMode::Implied, 2),
        0xEC => info(0xEC, Mnemonic::Cpx, AddressingMode::Absolute, 4),
        0xED => info(0xED, Mnemonic::Sbc, AddressingMode::Absolute, 4),
        0xEE => info(0xEE, Mnemonic::Inc, AddressingMode::Absolute, 6),
        0xEF => info(0xEF, Mnemonic::Isc, AddressingMode::Absolute, 6),
        0xF0 => info(0xF0, Mnemonic::Beq, AddressingMode::Relative, 2),
        0xF1 => info(0xF1, Mnemonic::Sbc, AddressingMode::IndirectIndexed, 5),
        0xF3 => info(0xF3, Mnemonic::Isc, AddressingMode::IndirectIndexed, 8),
        0xF5 => info(0xF5, Mnemonic::Sbc, AddressingMode::ZeroPageX, 4),
        0xF6 => info(0xF6, Mnemonic::Inc, AddressingMode::ZeroPageX, 6),
        0xF7 => info(0xF7, Mnemonic::Isc, AddressingMode::ZeroPageX, 6),
        0xF8 => info(0xF8, Mnemonic::Sed, AddressingMode::Implied, 2),
        0xF9 => info(0xF9, Mnemonic::Sbc, AddressingMode::AbsoluteY, 4),
        0xFB => info(0xFB, Mnemonic::Isc, AddressingMode::AbsoluteY, 7),
        0xFD => info(0xFD, Mnemonic::Sbc, AddressingMode::AbsoluteX, 4),
        0xFE => info(0xFE, Mnemonic::Inc, AddressingMode::AbsoluteX, 7),
        0xFF => info(0xFF, Mnemonic::Isc, AddressingMode::AbsoluteX, 7),
        _ => info(opcode, Mnemonic::Illegal, AddressingMode::Implied, 1),
    }
}
