//! Opcode metadata for disassembly. Pure data — no execution logic.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AddressingMode {
    Implied,
    Accumulator,
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Relative,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndexedIndirect,
    IndirectIndexed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mnemonic {
    Adc,
    And,
    Asl,
    Bcc,
    Bcs,
    Beq,
    Bit,
    Bmi,
    Bne,
    Bpl,
    Brk,
    Bvc,
    Bvs,
    Clc,
    Cld,
    Cli,
    Clv,
    Cmp,
    Cpx,
    Cpy,
    Dec,
    Dex,
    Dey,
    Eor,
    Inc,
    Inx,
    Iny,
    Jmp,
    Jsr,
    Lda,
    Ldx,
    Ldy,
    Lsr,
    Nop,
    Ora,
    Pha,
    Php,
    Pla,
    Plp,
    Rol,
    Ror,
    Rti,
    Rts,
    Sbc,
    Sec,
    Sed,
    Sei,
    Sta,
    Stx,
    Sty,
    Tax,
    Tay,
    Tsx,
    Txa,
    Txs,
    Tya,
    // Unofficial
    Dcp,
    Isc,
    Lax,
    Rla,
    Rra,
    Sax,
    Slo,
    Sre,
    // Additional undocumented
    Alr,
    Anc,
    Arr,
    Illegal,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InstructionInfo {
    pub opcode: u8,
    pub mnemonic: Mnemonic,
    pub mode: AddressingMode,
    pub bytes: u8,
    pub cycles: u8,
}

impl AddressingMode {
    pub fn operand_count(&self) -> usize {
        match self {
            AddressingMode::Implied | AddressingMode::Accumulator => 0,
            AddressingMode::Immediate
            | AddressingMode::ZeroPage
            | AddressingMode::ZeroPageX
            | AddressingMode::ZeroPageY
            | AddressingMode::Relative
            | AddressingMode::IndexedIndirect
            | AddressingMode::IndirectIndexed => 1,
            AddressingMode::Absolute
            | AddressingMode::AbsoluteX
            | AddressingMode::AbsoluteY
            | AddressingMode::Indirect => 2,
        }
    }
}

const fn info(opcode: u8, mnemonic: Mnemonic, mode: AddressingMode, bytes: u8, cycles: u8) -> InstructionInfo {
    InstructionInfo {
        opcode,
        mnemonic,
        mode,
        bytes,
        cycles,
    }
}

/// Unified opcode metadata table. Covers all 256 opcodes.
#[rustfmt::skip]
static OPCODES: [InstructionInfo; 256] = [
    // 0x00-0x0F
    info(0x00, Mnemonic::Brk, AddressingMode::Implied, 1, 7),
    info(0x01, Mnemonic::Ora, AddressingMode::IndexedIndirect, 2, 6),
    info(0x02, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0x03, Mnemonic::Slo, AddressingMode::IndexedIndirect, 2, 8),
    info(0x04, Mnemonic::Nop, AddressingMode::ZeroPage, 2, 3),
    info(0x05, Mnemonic::Ora, AddressingMode::ZeroPage, 2, 3),
    info(0x06, Mnemonic::Asl, AddressingMode::ZeroPage, 2, 5),
    info(0x07, Mnemonic::Slo, AddressingMode::ZeroPage, 2, 5),
    info(0x08, Mnemonic::Php, AddressingMode::Implied, 1, 3),
    info(0x09, Mnemonic::Ora, AddressingMode::Immediate, 2, 2),
    info(0x0A, Mnemonic::Asl, AddressingMode::Accumulator, 1, 2),
    info(0x0B, Mnemonic::Anc, AddressingMode::Immediate, 2, 2),
    info(0x0C, Mnemonic::Nop, AddressingMode::Absolute, 3, 4),
    info(0x0D, Mnemonic::Ora, AddressingMode::Absolute, 3, 4),
    info(0x0E, Mnemonic::Asl, AddressingMode::Absolute, 3, 6),
    info(0x0F, Mnemonic::Slo, AddressingMode::Absolute, 3, 6),
    // 0x10-0x1F
    info(0x10, Mnemonic::Bpl, AddressingMode::Relative, 2, 2),
    info(0x11, Mnemonic::Ora, AddressingMode::IndirectIndexed, 2, 5),
    info(0x12, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0x13, Mnemonic::Slo, AddressingMode::IndirectIndexed, 2, 8),
    info(0x14, Mnemonic::Nop, AddressingMode::ZeroPage, 2, 3),
    info(0x15, Mnemonic::Ora, AddressingMode::ZeroPageX, 2, 4),
    info(0x16, Mnemonic::Asl, AddressingMode::ZeroPageX, 2, 6),
    info(0x17, Mnemonic::Slo, AddressingMode::ZeroPageX, 2, 6),
    info(0x18, Mnemonic::Clc, AddressingMode::Implied, 1, 2),
    info(0x19, Mnemonic::Ora, AddressingMode::AbsoluteY, 3, 4),
    info(0x1A, Mnemonic::Nop, AddressingMode::Implied, 1, 2),
    info(0x1B, Mnemonic::Slo, AddressingMode::AbsoluteY, 3, 7),
    info(0x1C, Mnemonic::Nop, AddressingMode::AbsoluteX, 3, 4),
    info(0x1D, Mnemonic::Ora, AddressingMode::AbsoluteX, 3, 4),
    info(0x1E, Mnemonic::Asl, AddressingMode::AbsoluteX, 3, 7),
    info(0x1F, Mnemonic::Slo, AddressingMode::AbsoluteX, 3, 7),
    // 0x20-0x2F
    info(0x20, Mnemonic::Jsr, AddressingMode::Absolute, 3, 6),
    info(0x21, Mnemonic::And, AddressingMode::IndexedIndirect, 2, 6),
    info(0x22, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0x23, Mnemonic::Rla, AddressingMode::IndexedIndirect, 2, 8),
    info(0x24, Mnemonic::Bit, AddressingMode::ZeroPage, 2, 3),
    info(0x25, Mnemonic::And, AddressingMode::ZeroPage, 2, 3),
    info(0x26, Mnemonic::Rol, AddressingMode::ZeroPage, 2, 5),
    info(0x27, Mnemonic::Rla, AddressingMode::ZeroPage, 2, 5),
    info(0x28, Mnemonic::Plp, AddressingMode::Implied, 1, 4),
    info(0x29, Mnemonic::And, AddressingMode::Immediate, 2, 2),
    info(0x2A, Mnemonic::Rol, AddressingMode::Accumulator, 1, 2),
    info(0x2B, Mnemonic::Anc, AddressingMode::Immediate, 2, 2),
    info(0x2C, Mnemonic::Bit, AddressingMode::Absolute, 3, 4),
    info(0x2D, Mnemonic::And, AddressingMode::Absolute, 3, 4),
    info(0x2E, Mnemonic::Rol, AddressingMode::Absolute, 3, 6),
    info(0x2F, Mnemonic::Rla, AddressingMode::Absolute, 3, 6),
    // 0x30-0x3F
    info(0x30, Mnemonic::Bmi, AddressingMode::Relative, 2, 2),
    info(0x31, Mnemonic::And, AddressingMode::IndirectIndexed, 2, 5),
    info(0x32, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0x33, Mnemonic::Rla, AddressingMode::IndirectIndexed, 2, 8),
    info(0x34, Mnemonic::Nop, AddressingMode::ZeroPage, 2, 3),
    info(0x35, Mnemonic::And, AddressingMode::ZeroPageX, 2, 4),
    info(0x36, Mnemonic::Rol, AddressingMode::ZeroPageX, 2, 6),
    info(0x37, Mnemonic::Rla, AddressingMode::ZeroPageX, 2, 6),
    info(0x38, Mnemonic::Sec, AddressingMode::Implied, 1, 2),
    info(0x39, Mnemonic::And, AddressingMode::AbsoluteY, 3, 4),
    info(0x3A, Mnemonic::Nop, AddressingMode::Implied, 1, 2),
    info(0x3B, Mnemonic::Rla, AddressingMode::AbsoluteY, 3, 7),
    info(0x3C, Mnemonic::Nop, AddressingMode::AbsoluteX, 3, 4),
    info(0x3D, Mnemonic::And, AddressingMode::AbsoluteX, 3, 4),
    info(0x3E, Mnemonic::Rol, AddressingMode::AbsoluteX, 3, 7),
    info(0x3F, Mnemonic::Rla, AddressingMode::AbsoluteX, 3, 7),
    // 0x40-0x4F
    info(0x40, Mnemonic::Rti, AddressingMode::Implied, 1, 6),
    info(0x41, Mnemonic::Eor, AddressingMode::IndexedIndirect, 2, 6),
    info(0x42, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0x43, Mnemonic::Sre, AddressingMode::IndexedIndirect, 2, 8),
    info(0x44, Mnemonic::Nop, AddressingMode::ZeroPage, 2, 3),
    info(0x45, Mnemonic::Eor, AddressingMode::ZeroPage, 2, 3),
    info(0x46, Mnemonic::Lsr, AddressingMode::ZeroPage, 2, 5),
    info(0x47, Mnemonic::Sre, AddressingMode::ZeroPage, 2, 5),
    info(0x48, Mnemonic::Pha, AddressingMode::Implied, 1, 3),
    info(0x49, Mnemonic::Eor, AddressingMode::Immediate, 2, 2),
    info(0x4A, Mnemonic::Lsr, AddressingMode::Accumulator, 1, 2),
    info(0x4B, Mnemonic::Alr, AddressingMode::Immediate, 2, 2),
    info(0x4C, Mnemonic::Jmp, AddressingMode::Absolute, 3, 3),
    info(0x4D, Mnemonic::Eor, AddressingMode::Absolute, 3, 4),
    info(0x4E, Mnemonic::Lsr, AddressingMode::Absolute, 3, 6),
    info(0x4F, Mnemonic::Sre, AddressingMode::Absolute, 3, 6),
    // 0x50-0x5F
    info(0x50, Mnemonic::Bvc, AddressingMode::Relative, 2, 2),
    info(0x51, Mnemonic::Eor, AddressingMode::IndirectIndexed, 2, 5),
    info(0x52, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0x53, Mnemonic::Sre, AddressingMode::IndirectIndexed, 2, 8),
    info(0x54, Mnemonic::Nop, AddressingMode::ZeroPageX, 2, 4),
    info(0x55, Mnemonic::Eor, AddressingMode::ZeroPageX, 2, 4),
    info(0x56, Mnemonic::Lsr, AddressingMode::ZeroPageX, 2, 6),
    info(0x57, Mnemonic::Sre, AddressingMode::ZeroPageX, 2, 6),
    info(0x58, Mnemonic::Cli, AddressingMode::Implied, 1, 2),
    info(0x59, Mnemonic::Eor, AddressingMode::AbsoluteY, 3, 4),
    info(0x5A, Mnemonic::Nop, AddressingMode::Implied, 1, 2),
    info(0x5B, Mnemonic::Sre, AddressingMode::AbsoluteY, 3, 7),
    info(0x5C, Mnemonic::Nop, AddressingMode::AbsoluteX, 3, 4),
    info(0x5D, Mnemonic::Eor, AddressingMode::AbsoluteX, 3, 4),
    info(0x5E, Mnemonic::Lsr, AddressingMode::AbsoluteX, 3, 7),
    info(0x5F, Mnemonic::Sre, AddressingMode::AbsoluteX, 3, 7),
    // 0x60-0x6F
    info(0x60, Mnemonic::Rts, AddressingMode::Implied, 1, 6),
    info(0x61, Mnemonic::Adc, AddressingMode::IndexedIndirect, 2, 6),
    info(0x62, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0x63, Mnemonic::Rra, AddressingMode::IndexedIndirect, 2, 8),
    info(0x64, Mnemonic::Nop, AddressingMode::ZeroPage, 2, 3),
    info(0x65, Mnemonic::Adc, AddressingMode::ZeroPage, 2, 3),
    info(0x66, Mnemonic::Ror, AddressingMode::ZeroPage, 2, 5),
    info(0x67, Mnemonic::Rra, AddressingMode::ZeroPage, 2, 5),
    info(0x68, Mnemonic::Pla, AddressingMode::Implied, 1, 4),
    info(0x69, Mnemonic::Adc, AddressingMode::Immediate, 2, 2),
    info(0x6A, Mnemonic::Ror, AddressingMode::Accumulator, 1, 2),
    info(0x6B, Mnemonic::Arr, AddressingMode::Immediate, 2, 2),
    info(0x6C, Mnemonic::Jmp, AddressingMode::Indirect, 3, 5),
    info(0x6D, Mnemonic::Adc, AddressingMode::Absolute, 3, 4),
    info(0x6E, Mnemonic::Ror, AddressingMode::Absolute, 3, 6),
    info(0x6F, Mnemonic::Rra, AddressingMode::Absolute, 3, 6),
    // 0x70-0x7F
    info(0x70, Mnemonic::Bvs, AddressingMode::Relative, 2, 2),
    info(0x71, Mnemonic::Adc, AddressingMode::IndirectIndexed, 2, 5),
    info(0x72, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0x73, Mnemonic::Rra, AddressingMode::IndirectIndexed, 2, 8),
    info(0x74, Mnemonic::Nop, AddressingMode::ZeroPageX, 2, 4),
    info(0x75, Mnemonic::Adc, AddressingMode::ZeroPageX, 2, 4),
    info(0x76, Mnemonic::Ror, AddressingMode::ZeroPageX, 2, 6),
    info(0x77, Mnemonic::Rra, AddressingMode::ZeroPageX, 2, 6),
    info(0x78, Mnemonic::Sei, AddressingMode::Implied, 1, 2),
    info(0x79, Mnemonic::Adc, AddressingMode::AbsoluteY, 3, 4),
    info(0x7A, Mnemonic::Nop, AddressingMode::Implied, 1, 2),
    info(0x7B, Mnemonic::Rra, AddressingMode::AbsoluteY, 3, 7),
    info(0x7C, Mnemonic::Nop, AddressingMode::AbsoluteX, 3, 4),
    info(0x7D, Mnemonic::Adc, AddressingMode::AbsoluteX, 3, 4),
    info(0x7E, Mnemonic::Ror, AddressingMode::AbsoluteX, 3, 7),
    info(0x7F, Mnemonic::Rra, AddressingMode::AbsoluteX, 3, 7),
    // 0x80-0x8F
    info(0x80, Mnemonic::Nop, AddressingMode::Immediate, 2, 2),
    info(0x81, Mnemonic::Sta, AddressingMode::IndexedIndirect, 2, 6),
    info(0x82, Mnemonic::Nop, AddressingMode::Immediate, 2, 2),
    info(0x83, Mnemonic::Sax, AddressingMode::IndexedIndirect, 2, 6),
    info(0x84, Mnemonic::Sty, AddressingMode::ZeroPage, 2, 3),
    info(0x85, Mnemonic::Sta, AddressingMode::ZeroPage, 2, 3),
    info(0x86, Mnemonic::Stx, AddressingMode::ZeroPage, 2, 3),
    info(0x87, Mnemonic::Sax, AddressingMode::ZeroPage, 2, 3),
    info(0x88, Mnemonic::Dey, AddressingMode::Implied, 1, 2),
    info(0x89, Mnemonic::Nop, AddressingMode::Immediate, 2, 2),
    info(0x8A, Mnemonic::Txa, AddressingMode::Implied, 1, 2),
    info(0x8B, Mnemonic::Illegal, AddressingMode::Immediate, 2, 2),  // XAA/ANE
    info(0x8C, Mnemonic::Sty, AddressingMode::Absolute, 3, 4),
    info(0x8D, Mnemonic::Sta, AddressingMode::Absolute, 3, 4),
    info(0x8E, Mnemonic::Stx, AddressingMode::Absolute, 3, 4),
    info(0x8F, Mnemonic::Sax, AddressingMode::Absolute, 3, 4),
    // 0x90-0x9F
    info(0x90, Mnemonic::Bcc, AddressingMode::Relative, 2, 2),
    info(0x91, Mnemonic::Sta, AddressingMode::IndirectIndexed, 2, 6),
    info(0x92, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0x93, Mnemonic::Illegal, AddressingMode::IndirectIndexed, 2, 6),  // AHX (indirect),Y
    info(0x94, Mnemonic::Sty, AddressingMode::ZeroPageX, 2, 4),
    info(0x95, Mnemonic::Sta, AddressingMode::ZeroPageX, 2, 4),
    info(0x96, Mnemonic::Stx, AddressingMode::ZeroPageY, 2, 4),
    info(0x97, Mnemonic::Sax, AddressingMode::ZeroPageY, 2, 4),
    info(0x98, Mnemonic::Tya, AddressingMode::Implied, 1, 2),
    info(0x99, Mnemonic::Sta, AddressingMode::AbsoluteY, 3, 5),
    info(0x9A, Mnemonic::Txs, AddressingMode::Implied, 1, 2),
    info(0x9B, Mnemonic::Illegal, AddressingMode::AbsoluteY, 3, 5),  // TAS/SHS
    info(0x9C, Mnemonic::Illegal, AddressingMode::AbsoluteX, 3, 5),  // SHY/SYA
    info(0x9D, Mnemonic::Sta, AddressingMode::AbsoluteX, 3, 5),
    info(0x9E, Mnemonic::Illegal, AddressingMode::AbsoluteY, 3, 5),  // SHX/SXA
    info(0x9F, Mnemonic::Illegal, AddressingMode::AbsoluteY, 3, 5),  // AHX/SHA abs,Y
    // 0xA0-0xAF
    info(0xA0, Mnemonic::Ldy, AddressingMode::Immediate, 2, 2),
    info(0xA1, Mnemonic::Lda, AddressingMode::IndexedIndirect, 2, 6),
    info(0xA2, Mnemonic::Ldx, AddressingMode::Immediate, 2, 2),
    info(0xA3, Mnemonic::Lax, AddressingMode::IndexedIndirect, 2, 6),
    info(0xA4, Mnemonic::Ldy, AddressingMode::ZeroPage, 2, 3),
    info(0xA5, Mnemonic::Lda, AddressingMode::ZeroPage, 2, 3),
    info(0xA6, Mnemonic::Ldx, AddressingMode::ZeroPage, 2, 3),
    info(0xA7, Mnemonic::Lax, AddressingMode::ZeroPage, 2, 3),
    info(0xA8, Mnemonic::Tay, AddressingMode::Implied, 1, 2),
    info(0xA9, Mnemonic::Lda, AddressingMode::Immediate, 2, 2),
    info(0xAA, Mnemonic::Tax, AddressingMode::Implied, 1, 2),
    info(0xAB, Mnemonic::Lax, AddressingMode::Immediate, 2, 2),
    info(0xAC, Mnemonic::Ldy, AddressingMode::Absolute, 3, 4),
    info(0xAD, Mnemonic::Lda, AddressingMode::Absolute, 3, 4),
    info(0xAE, Mnemonic::Ldx, AddressingMode::Absolute, 3, 4),
    info(0xAF, Mnemonic::Lax, AddressingMode::Absolute, 3, 4),
    // 0xB0-0xBF
    info(0xB0, Mnemonic::Bcs, AddressingMode::Relative, 2, 2),
    info(0xB1, Mnemonic::Lda, AddressingMode::IndirectIndexed, 2, 5),
    info(0xB2, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0xB3, Mnemonic::Lax, AddressingMode::IndirectIndexed, 2, 5),
    info(0xB4, Mnemonic::Ldy, AddressingMode::ZeroPageX, 2, 4),
    info(0xB5, Mnemonic::Lda, AddressingMode::ZeroPageX, 2, 4),
    info(0xB6, Mnemonic::Ldx, AddressingMode::ZeroPageY, 2, 4),
    info(0xB7, Mnemonic::Lax, AddressingMode::ZeroPageY, 2, 4),
    info(0xB8, Mnemonic::Clv, AddressingMode::Implied, 1, 2),
    info(0xB9, Mnemonic::Lda, AddressingMode::AbsoluteY, 3, 4),
    info(0xBA, Mnemonic::Tsx, AddressingMode::Implied, 1, 2),
    info(0xBB, Mnemonic::Illegal, AddressingMode::AbsoluteY, 3, 4),  // LAS/LAE
    info(0xBC, Mnemonic::Ldy, AddressingMode::AbsoluteX, 3, 4),
    info(0xBD, Mnemonic::Lda, AddressingMode::AbsoluteX, 3, 4),
    info(0xBE, Mnemonic::Ldx, AddressingMode::AbsoluteY, 3, 4),
    info(0xBF, Mnemonic::Lax, AddressingMode::AbsoluteY, 3, 4),
    // 0xC0-0xCF
    info(0xC0, Mnemonic::Cpy, AddressingMode::Immediate, 2, 2),
    info(0xC1, Mnemonic::Cmp, AddressingMode::IndexedIndirect, 2, 6),
    info(0xC2, Mnemonic::Nop, AddressingMode::Immediate, 2, 2),
    info(0xC3, Mnemonic::Dcp, AddressingMode::IndexedIndirect, 2, 8),
    info(0xC4, Mnemonic::Cpy, AddressingMode::ZeroPage, 2, 3),
    info(0xC5, Mnemonic::Cmp, AddressingMode::ZeroPage, 2, 3),
    info(0xC6, Mnemonic::Dec, AddressingMode::ZeroPage, 2, 5),
    info(0xC7, Mnemonic::Dcp, AddressingMode::ZeroPage, 2, 5),
    info(0xC8, Mnemonic::Iny, AddressingMode::Implied, 1, 2),
    info(0xC9, Mnemonic::Cmp, AddressingMode::Immediate, 2, 2),
    info(0xCA, Mnemonic::Dex, AddressingMode::Implied, 1, 2),
    info(0xCB, Mnemonic::Illegal, AddressingMode::Immediate, 2, 2),  // SBX/AXS
    info(0xCC, Mnemonic::Cpy, AddressingMode::Absolute, 3, 4),
    info(0xCD, Mnemonic::Cmp, AddressingMode::Absolute, 3, 4),
    info(0xCE, Mnemonic::Dec, AddressingMode::Absolute, 3, 6),
    info(0xCF, Mnemonic::Dcp, AddressingMode::Absolute, 3, 6),
    // 0xD0-0xDF
    info(0xD0, Mnemonic::Bne, AddressingMode::Relative, 2, 2),
    info(0xD1, Mnemonic::Cmp, AddressingMode::IndirectIndexed, 2, 5),
    info(0xD2, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0xD3, Mnemonic::Dcp, AddressingMode::IndirectIndexed, 2, 8),
    info(0xD4, Mnemonic::Nop, AddressingMode::ZeroPageX, 2, 4),
    info(0xD5, Mnemonic::Cmp, AddressingMode::ZeroPageX, 2, 4),
    info(0xD6, Mnemonic::Dec, AddressingMode::ZeroPageX, 2, 6),
    info(0xD7, Mnemonic::Dcp, AddressingMode::ZeroPageX, 2, 6),
    info(0xD8, Mnemonic::Cld, AddressingMode::Implied, 1, 2),
    info(0xD9, Mnemonic::Cmp, AddressingMode::AbsoluteY, 3, 4),
    info(0xDA, Mnemonic::Nop, AddressingMode::Implied, 1, 2),
    info(0xDB, Mnemonic::Dcp, AddressingMode::AbsoluteY, 3, 7),
    info(0xDC, Mnemonic::Nop, AddressingMode::AbsoluteX, 3, 4),
    info(0xDD, Mnemonic::Cmp, AddressingMode::AbsoluteX, 3, 4),
    info(0xDE, Mnemonic::Dec, AddressingMode::AbsoluteX, 3, 7),
    info(0xDF, Mnemonic::Dcp, AddressingMode::AbsoluteX, 3, 7),
    // 0xE0-0xEF
    info(0xE0, Mnemonic::Cpx, AddressingMode::Immediate, 2, 2),
    info(0xE1, Mnemonic::Sbc, AddressingMode::IndexedIndirect, 2, 6),
    info(0xE2, Mnemonic::Nop, AddressingMode::Immediate, 2, 2),
    info(0xE3, Mnemonic::Isc, AddressingMode::IndexedIndirect, 2, 8),
    info(0xE4, Mnemonic::Cpx, AddressingMode::ZeroPage, 2, 3),
    info(0xE5, Mnemonic::Sbc, AddressingMode::ZeroPage, 2, 3),
    info(0xE6, Mnemonic::Inc, AddressingMode::ZeroPage, 2, 5),
    info(0xE7, Mnemonic::Isc, AddressingMode::ZeroPage, 2, 5),
    info(0xE8, Mnemonic::Inx, AddressingMode::Implied, 1, 2),
    info(0xE9, Mnemonic::Sbc, AddressingMode::Immediate, 2, 2),
    info(0xEA, Mnemonic::Nop, AddressingMode::Implied, 1, 2),
    info(0xEB, Mnemonic::Sbc, AddressingMode::Immediate, 2, 2),
    info(0xEC, Mnemonic::Cpx, AddressingMode::Absolute, 3, 4),
    info(0xED, Mnemonic::Sbc, AddressingMode::Absolute, 3, 4),
    info(0xEE, Mnemonic::Inc, AddressingMode::Absolute, 3, 6),
    info(0xEF, Mnemonic::Isc, AddressingMode::Absolute, 3, 6),
    // 0xF0-0xFF
    info(0xF0, Mnemonic::Beq, AddressingMode::Relative, 2, 2),
    info(0xF1, Mnemonic::Sbc, AddressingMode::IndirectIndexed, 2, 5),
    info(0xF2, Mnemonic::Illegal, AddressingMode::Implied, 1, 2),  // JAM
    info(0xF3, Mnemonic::Isc, AddressingMode::IndirectIndexed, 2, 8),
    info(0xF4, Mnemonic::Nop, AddressingMode::ZeroPageX, 2, 4),
    info(0xF5, Mnemonic::Sbc, AddressingMode::ZeroPageX, 2, 4),
    info(0xF6, Mnemonic::Inc, AddressingMode::ZeroPageX, 2, 6),
    info(0xF7, Mnemonic::Isc, AddressingMode::ZeroPageX, 2, 6),
    info(0xF8, Mnemonic::Sed, AddressingMode::Implied, 1, 2),
    info(0xF9, Mnemonic::Sbc, AddressingMode::AbsoluteY, 3, 4),
    info(0xFA, Mnemonic::Nop, AddressingMode::Implied, 1, 2),
    info(0xFB, Mnemonic::Isc, AddressingMode::AbsoluteY, 3, 7),
    info(0xFC, Mnemonic::Nop, AddressingMode::AbsoluteX, 3, 4),
    info(0xFD, Mnemonic::Sbc, AddressingMode::AbsoluteX, 3, 4),
    info(0xFE, Mnemonic::Inc, AddressingMode::AbsoluteX, 3, 7),
    info(0xFF, Mnemonic::Isc, AddressingMode::AbsoluteX, 3, 7),
];

pub const fn decode(opcode: u8) -> InstructionInfo {
    OPCODES[opcode as usize]
}
